export const siteOrigin = 'https://www.thecollegedate.com';

export const seoPages = [
  { path: '/', source: 'index.html', changefreq: 'weekly', priority: '1.0' },
  { path: '/child-safety-standards', source: 'public/child-safety-standards.html', changefreq: 'yearly', priority: '0.2' },
  { path: '/about', source: 'public/about.html', changefreq: 'monthly', priority: '0.8' },
  { path: '/the-college-date', source: 'public/the-college-date.html', changefreq: 'monthly', priority: '0.86' },
  { path: '/what-is-the-college-date', source: 'public/what-is-the-college-date.html', changefreq: 'monthly', priority: '0.84' },
  { path: '/faq', source: 'public/faq.html', changefreq: 'monthly', priority: '0.82' },
  { path: '/download', source: 'public/download.html', changefreq: 'monthly', priority: '0.83' },
  { path: '/college-date', source: 'public/college-date.html', changefreq: 'monthly', priority: '0.82' },
  { path: '/cd-app', source: 'public/cd-app.html', changefreq: 'monthly', priority: '0.64' },
  { path: '/press', source: 'public/press.html', changefreq: 'monthly', priority: '0.72' },
  { path: '/campus-dating', source: 'public/campus-dating.html', changefreq: 'monthly', priority: '0.8' },
  { path: '/student-dating', source: 'public/student-dating.html', changefreq: 'monthly', priority: '0.8' },
  { path: '/safety', source: 'public/safety.html', changefreq: 'monthly', priority: '0.5' },
  { path: '/support', source: 'public/support.html', changefreq: 'monthly', priority: '0.5' },
  { path: '/privacy', source: 'public/privacy.html', changefreq: 'yearly', priority: '0.45' },
  { path: '/terms', source: 'public/terms.html', changefreq: 'yearly', priority: '0.4' },
  { path: '/delete-account', source: 'public/delete-account.html', changefreq: 'yearly', priority: '0.4' },
  { path: '/college-dating-app', source: 'public/college-dating-app.html', changefreq: 'monthly', priority: '0.8' },
  { path: '/dating-app-for-students', source: 'public/dating-app-for-students.html', changefreq: 'monthly', priority: '0.8' },
  { path: '/campus-dating-safety', source: 'public/campus-dating-safety.html', changefreq: 'monthly', priority: '0.6' },
  { path: '/nigeria-dating-app', source: 'public/nigeria-dating-app.html', changefreq: 'monthly', priority: '0.85' },
  { path: '/dating-app-in-nigeria', source: 'public/dating-app-in-nigeria.html', changefreq: 'monthly', priority: '0.85' },
  { path: '/university-dating-nigeria', source: 'public/university-dating-nigeria.html', changefreq: 'monthly', priority: '0.8' },
  { path: '/dating-app-for-university-students-nigeria', source: 'public/dating-app-for-university-students-nigeria.html', changefreq: 'monthly', priority: '0.82' },
  { path: '/safe-dating-app-nigeria', source: 'public/safe-dating-app-nigeria.html', changefreq: 'monthly', priority: '0.78' },
  { path: '/campus-dating-app-lagos', source: 'public/campus-dating-app-lagos.html', changefreq: 'monthly', priority: '0.74' },
  { path: '/serious-relationship-app-nigeria-students', source: 'public/serious-relationship-app-nigeria-students.html', changefreq: 'monthly', priority: '0.74' },
  { path: '/best-dating-site-for-students-nigeria', source: 'public/best-dating-site-for-students-nigeria.html', changefreq: 'monthly', priority: '0.76' },
  { path: '/online-dating-app-for-undergraduates', source: 'public/online-dating-app-for-undergraduates.html', changefreq: 'monthly', priority: '0.74' },
  { path: '/how-to-meet-people-on-campus', source: 'public/how-to-meet-people-on-campus.html', changefreq: 'monthly', priority: '0.7' },
  { path: '/dating-as-a-fresher-nigeria', source: 'public/dating-as-a-fresher-nigeria.html', changefreq: 'monthly', priority: '0.7' },
  { path: '/dating-profile-picture-tips-students', source: 'public/dating-profile-picture-tips-students.html', changefreq: 'monthly', priority: '0.7' },
  { path: '/first-message-examples-dating-apps', source: 'public/first-message-examples-dating-apps.html', changefreq: 'monthly', priority: '0.7' },
  { path: '/romance-scams-nigerian-students', source: 'public/romance-scams-nigerian-students.html', changefreq: 'monthly', priority: '0.68' },
  { path: '/what-not-to-share-on-dating-apps', source: 'public/what-not-to-share-on-dating-apps.html', changefreq: 'monthly', priority: '0.68' },
  { path: '/campus-date-ideas-students', source: 'public/campus-date-ideas-students.html', changefreq: 'monthly', priority: '0.7' },
  { path: '/relationship-boundaries-for-students', source: 'public/relationship-boundaries-for-students.html', changefreq: 'monthly', priority: '0.7' },
  { path: '/green-flags-student-relationships', source: 'public/green-flags-student-relationships.html', changefreq: 'monthly', priority: '0.7' },
  { path: '/blog', source: 'public/blog.html', changefreq: 'weekly', priority: '0.75' },
  { path: '/blog/best-dating-apps-nigeria-students', source: 'public/blog/best-dating-apps-nigeria-students.html', changefreq: 'monthly', priority: '0.75' },
  { path: '/blog/online-dating-for-nigerian-students', source: 'public/blog/online-dating-for-nigerian-students.html', changefreq: 'monthly', priority: '0.75' },
  { path: '/blog/how-to-date-safely-on-campus-nigeria', source: 'public/blog/how-to-date-safely-on-campus-nigeria.html', changefreq: 'monthly', priority: '0.7' },
  { path: '/dating-bio-examples-students', source: 'public/dating-bio-examples-students.html', changefreq: 'monthly', priority: '0.72' },
  { path: '/tools/dating-bio-generator', source: 'public/tools/dating-bio-generator.html', changefreq: 'monthly', priority: '0.72' },
  { path: '/conversation-starters-dating-app', source: 'public/conversation-starters-dating-app.html', changefreq: 'monthly', priority: '0.72' },
  { path: '/first-date-ideas-students', source: 'public/first-date-ideas-students.html', changefreq: 'monthly', priority: '0.72' },
];

export const appShellRoutes = [
  '/login',
  '/signup',
  '/dashboard',
  '/match',
  '/explore',
  '/chat',
  '/messages',
  '/messages/*',
  '/status',
  '/snap',
  '/profile/*',
  '/settings',
  '/referrals',
  '/wallet',
  '/requests',
  '/leaderboard',
  '/confessions',
  '/premium',
  '/viewers',
  '/notifications',
  '/mini-profile-setup',
  '/call/*',
  '/admin',
  '/auth/callback',
  '/payment/callback',
  '/wireframes',
  '/notification-preview',
  '/notification-preview-lab',
  '/push-preview',
  '/push-lab',
];

export const privateNoindexRoutes = [
  '/login',
  '/signup',
  '/dashboard',
  '/match',
  '/explore',
  '/chat',
  '/messages',
  '/messages/*',
  '/status',
  '/snap',
  '/profile/*',
  '/settings',
  '/referrals',
  '/wallet',
  '/requests',
  '/leaderboard',
  '/confessions',
  '/premium',
  '/viewers',
  '/notifications',
  '/mini-profile-setup',
  '/call/*',
  '/admin',
  '/auth/callback',
  '/payment/callback',
  '/wireframes',
  '/notification-preview',
  '/notification-preview-lab',
  '/push-preview',
  '/push-lab',
];
